#!/usr/bin/env python3
"""
merge_sources.py - Automatically generates api/data.generated.js
Reads all *_articles.json files and embeds them into data.generated.js
Run this after scraping to update your bot's data
"""

import json
import glob
import os
from datetime import datetime
import hashlib
from urllib.parse import urlparse

# ============================================
# CONFIGURATION
# ============================================

OUTPUT_FILE = "data.generated.js" 
SOURCE_PATTERNS = ["*_articles.json"]  # Finds ALL *_articles.json files

# ============================================
# FUNCTIONS
# ============================================

def find_json_files():
    """Find all JSON files matching patterns."""
    files = []
    for pattern in SOURCE_PATTERNS:
        files.extend(glob.glob(pattern))
    return files

def load_json(filepath):
    """Load JSON file with error handling."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"⚠️ Error loading {filepath}: {e}")
        return None

def extract_articles(data):
    """Extract articles from JSON data."""
    if isinstance(data, list):
        return data
    elif isinstance(data, dict):
        if 'articles' in data:
            return data['articles']
    return []

def normalize_article(article):
    """Ensure consistent field names."""
    normalized = {}
    
    field_map = {
        'title': ['title', 'headline', 'name'],
        'author': ['author', 'creator', 'writer', 'byline'],
        'date': ['date', 'published', 'pubDate', 'created'],
        'content': ['content', 'description', 'summary', 'body', 'text'],
        'url': ['url', 'link', 'href', 'source_url'],
        'source_name': ['source_name', 'source', 'publisher'],
        'source_type': ['source_type', 'type'],
        'word_count': ['word_count', 'words'],
        'domain': ['domain'],
    }
    
    for target, sources in field_map.items():
        for source in sources:
            if source in article and article[source]:
                normalized[target] = article[source]
                break
        if target not in normalized:
            # Set defaults
            defaults = {
                'title': 'Untitled',
                'author': 'Unknown',
                'source_name': 'Unknown',
                'source_type': 'blog',
                'word_count': 0,
                'url': '#',
                'date': datetime.now().isoformat(),
                'domain': 'unknown'
            }
            normalized[target] = defaults.get(target, '')
    
    # Generate hash
    if 'hash' not in normalized:
        url = normalized.get('url', '')
        if url and url != '#':
            normalized['hash'] = hashlib.md5(url.encode()).hexdigest()[:8]
        else:
            normalized['hash'] = hashlib.md5(normalized['title'].encode()).hexdigest()[:8]
    
    # Add timestamp
    if 'timestamp' not in normalized:
        normalized['timestamp'] = datetime.now().isoformat()
    
    return normalized

def generate_data_js(articles, source_stats):
    """Generate api/data.generated.js."""
    
    js_content = f"""// api/data.generated.js - AUTO-GENERATED by merge_sources.py
// DO NOT EDIT - This file is automatically updated
// Generated: {datetime.now().isoformat()}
// Total Sources: {len(articles)}

const techCrunchData = {{
  source: "Multi-Source AI News",
  source_url: "https://techcrunch.com/category/artificial-intelligence/",
  total_sources: {len(articles)},
  source_stats: {json.dumps(source_stats, indent=2)},
  last_updated: "{datetime.now().isoformat()}",
  articles: {json.dumps(articles, indent=2)}
}};

export {{ techCrunchData }};
export default techCrunchData;
"""
    
    # Ensure api directory exists
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"✅ Generated {OUTPUT_FILE} with {len(articles)} articles")
    return len(articles)

def main():
    """Main execution."""
    print("=" * 60)
    print("📊 AI News Source Merger")
    print(f"📅 Started at: {datetime.now().isoformat()}")
    print("=" * 60)
    
    # Find all JSON files
    json_files = find_json_files()
    print(f"\n📁 Found {len(json_files)} JSON files:")
    for f in json_files:
        print(f"   - {f}")
    
    # Load all articles
    all_articles = []
    source_stats = {}
    
    for filepath in json_files:
        data = load_json(filepath)
        if data:
            articles = extract_articles(data)
            if articles:
                source_name = os.path.splitext(os.path.basename(filepath))[0]
                count = 0
                for article in articles:
                    normalized = normalize_article(article)
                    all_articles.append(normalized)
                    count += 1
                source_stats[source_name] = count
                print(f"✅ Loaded {count} articles from {filepath}")
    
    # Remove duplicates by URL
    unique_articles = []
    seen_urls = set()
    for article in all_articles:
        url = article.get('url', '')
        if url and url not in seen_urls:
            seen_urls.add(url)
            unique_articles.append(article)
        elif not url or url == '#':
            unique_articles.append(article)
    
    # Remove duplicates by title
    seen_titles = set()
    final_articles = []
    for article in unique_articles:
        title = article.get('title', '').lower().strip()
        if title and title not in seen_titles:
            seen_titles.add(title)
            final_articles.append(article)
        elif not title:
            final_articles.append(article)
    
    # Generate the data file
    total = generate_data_js(final_articles, source_stats)
    
    # Summary
    print("\n" + "=" * 60)
    print("📊 MERGE SUMMARY")
    print("=" * 60)
    print(f"   Total articles loaded: {len(all_articles)}")
    print(f"   Duplicates removed: {len(all_articles) - len(final_articles)}")
    print(f"   Final unique articles: {len(final_articles)}")
    print("\n   Source Breakdown:")
    for source, count in source_stats.items():
        print(f"   - {source}: {count} articles")
    print(f"\n   📁 Output: {OUTPUT_FILE}")
    print(f"   📅 Completed at: {datetime.now().isoformat()}")

if __name__ == "__main__":
    main()
