// api/data.js - API Handler Only
// Data is auto-generated by merge_sources.py

// ============================================
// IMPORT PROMPTS
// ============================================

import { systemPrompts, selectPrompt } from './prompts/system.js';
import { getFewShotExamples } from './prompts/examples.js';
import { selectTemplate } from './prompts/templates.js';

// ============================================
// DATA - Imported from auto-generated data
// ============================================

// This will be generated by merge_sources.py
import { techCrunchData } from './data.generated.js';

// For backward compatibility - if data.generated.js doesn't exist yet
let sources = [];
let sourceStats = {};
let lastUpdated = new Date().toISOString();

try {
  if (techCrunchData && techCrunchData.articles) {
    sources = techCrunchData.articles;
    sourceStats = techCrunchData.source_stats || {};
    lastUpdated = techCrunchData.last_updated || new Date().toISOString();
  }
} catch (e) {
  console.warn('⚠️ Using fallback data - run merge_sources.py to generate fresh data');
  // Fallback data - will be replaced when merge_sources.py runs
  sources = [];
  sourceStats = { total: 0 };
}

// ============================================
// CLASSIFY QUERY TYPE
// ============================================

function classifyQuery(query) {
  const lower = query.toLowerCase();
  
  const categories = {
    factual: { keywords: ['what', 'when', 'where', 'who', 'which', 'is', 'are', 'was', 'were', 'did'], weight: 1 },
    analytical: { keywords: ['compare', 'contrast', 'analyze', 'synthesis', 'trend', 'pattern', 'relationship', 'impact', 'cause'], weight: 1.5 },
    comparative: { keywords: ['better', 'best', 'worst', 'top', 'vs', 'versus', 'compared to', 'difference'], weight: 1.5 },
    exploratory: { keywords: ['how does', 'why does', 'what if', 'could', 'would', 'might', 'imagine'], weight: 1.2 },
    summarization: { keywords: ['summarize', 'summarise', 'brief', 'overview', 'key points', 'main ideas', 'tl;dr'], weight: 1.3 }
  };
  
  let scores = {};
  let bestCategory = 'factual';
  let bestScore = 0;
  
  for (const [category, data] of Object.entries(categories)) {
    let score = 0;
    for (const keyword of data.keywords) {
      if (lower.includes(keyword)) score += 1;
    }
    scores[category] = score * data.weight;
    if (scores[category] > bestScore) {
      bestScore = scores[category];
      bestCategory = category;
    }
  }
  
  if (bestScore === 0) {
    bestCategory = 'factual';
    bestScore = 0.5;
  }
  
  return {
    type: bestCategory,
    confidence: Math.min(bestScore / 3, 1),
    scores: scores
  };
}

// ============================================
// SEARCH FUNCTION
// ============================================

function searchSources(query, sourcesList) {
  if (!query) return { results: [], classification: null };
  
  const queryLower = query.toLowerCase().trim();
  if (queryLower.length < 2) return { results: [], classification: null };
  
  const classification = classifyQuery(query);
  
  const results = [];
  const words = queryLower.split(/\s+/).filter(w => w.length > 2);
  
  for (const source of sourcesList) {
    const content = (source.content || '').toLowerCase();
    const title = (source.title || '').toLowerCase();
    const sourceName = (source.source_name || '').toLowerCase();
    
    let score = 0;
    
    if (title.includes(queryLower)) score += 30;
    if (sourceName.includes(queryLower)) score += 20;
    
    for (const word of words) {
      const count = (content.match(new RegExp(word, 'g')) || []).length;
      score += count * 3;
    }
    
    if (content.includes(queryLower)) score += 15;
    
    if (score > 0) {
      let chunk = '';
      const sentences = content.split(/[.!?]+/);
      for (const sentence of sentences) {
        if (sentence.includes(queryLower) || words.some(w => sentence.includes(w))) {
          chunk = sentence.trim();
          break;
        }
      }
      if (!chunk) {
        chunk = (source.content || '').substring(0, 300);
      }
      
      const relevance = Math.min(Math.round((score / 50) * 100), 100);
      
      results.push({
        title: source.title || 'Untitled',
        source: source.url || '#',
        source_name: source.source_name || 'Unknown',
        author: source.author || 'Unknown',
        date: source.date || '',
        chunk: chunk + '...',
        relevance: relevance,
        score: score,
        domain: source.domain || 'unknown'
      });
    }
  }
  
  results.sort((a, b) => b.score - a.score);
  return {
    results: results.slice(0, 5),
    classification: classification
  };
}

// ============================================
// GENERATE RESPONSE
// ============================================

function generateResponse(query, searchResult) {
  const { results, classification } = searchResult;
  
  if (results.length === 0) {
    return {
      response: "🔍 **No matching content found.**\n\nTry asking about:\n- AI tools and platforms\n- ChatGPT, Claude, Gemini, or Grok\n- AI strategy and industry trends\n- Specific AI models or features",
      sources: [],
      metadata: {
        matches_found: 0,
        query_type: classification?.type || 'unknown',
        ai_generated: true
      }
    };
  }
  
  const queryType = classification?.type || 'factual';
  const promptConfig = selectPrompt(queryType);
  const examples = getFewShotExamples(queryType);
  
  let responseText = '';
  
  responseText += `**📊 Answer based on ${results.length} source(s):**\n\n`;
  
  if (examples && examples.length > 0) {
    const example = examples[0];
    responseText += `*Example format:*\n`;
    responseText += `Question: ${example.question}\n`;
    responseText += `Answer: ${example.answer}\n\n`;
  }
  
  for (let i = 0; i < results.length; i++) {
    const r = results[i];
    const relevanceEmoji = r.relevance > 60 ? '🟢' : r.relevance > 30 ? '🟡' : '🔴';
    const relevanceLabel = r.relevance > 60 ? 'High' : r.relevance > 30 ? 'Medium' : 'Low';
    
    responseText += `**Source ${i + 1}: ${r.title}**\n`;
    responseText += `🏷️ Source: ${r.source_name}\n`;
    responseText += `✍️ Author: ${r.author}\n`;
    responseText += `📅 Date: ${r.date}\n`;
    responseText += `📊 Relevance: ${relevanceEmoji} ${relevanceLabel} (${r.relevance}%)\n\n`;
    responseText += `${r.chunk}\n\n`;
    responseText += `🔗 ${r.source}\n\n---\n\n`;
  }
  
  responseText += `\n*Query Type: ${queryType} (Confidence: ${Math.round(classification?.confidence * 100 || 0)}%)*\n`;
  responseText += `*Temperature: ${promptConfig.temperature}, Max Tokens: ${promptConfig.max_tokens}*\n`;
  
  return {
    response: responseText,
    sources: results,
    metadata: {
      matches_found: results.length,
      query_type: queryType,
      query_confidence: classification?.confidence || 0,
      prompt_temperature: promptConfig.temperature,
      prompt_max_tokens: promptConfig.max_tokens,
      last_updated: lastUpdated,
      ai_generated: true
    }
  };
}

// ============================================
// API HANDLER - DEFAULT EXPORT
// ============================================

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'GET' && req.method !== 'POST') {
    return res.status(405).json({ 
      error: 'Method not allowed',
      allowed: ['GET', 'POST']
    });
  }

  try {
    let query = null;
    let action = null;

    if (req.method === 'GET') {
      query = req.query.query || null;
      action = req.query.action || null;
    } else {
      query = req.body?.query || null;
      action = req.body?.action || null;
    }

    // Health check
    if (action === 'health' || action === 'ping') {
      return res.status(200).json({
        status: 'ok',
        timestamp: new Date().toISOString(),
        total_sources: sources.length,
        source_stats: sourceStats,
        source_names: [...new Set(sources.map(s => s.source_name))],
        prompt_types: Object.keys(systemPrompts)
      });
    }

    // Get all sources
    if (action === 'all') {
      return res.status(200).json({
        total: sources.length,
        source_stats: sourceStats,
        sources: sources.map(s => ({
          title: s.title,
          source_name: s.source_name,
          author: s.author || 'Unknown',
          date: s.date || '',
          url: s.url,
          word_count: s.word_count || 0,
          domain: s.domain || 'unknown'
        }))
      });
    }

    // Get stats
    if (action === 'stats') {
      return res.status(200).json({
        total_sources: sources.length,
        source_stats: sourceStats,
        prompt_types: Object.keys(systemPrompts),
        last_updated: lastUpdated
      });
    }

    // Search
    if (query) {
      const searchResult = searchSources(query, sources);
      const response = generateResponse(query, searchResult);
      
      return res.status(200).json({
        ...response,
        metadata: {
          ...response.metadata,
          total_sources: sources.length,
          last_updated: lastUpdated
        }
      });
    }

    // Default response
    return res.status(200).json({
      name: 'Omni Brand Intelligence Bot API',
      version: '2.0.0',
      status: 'running',
      total_sources: sources.length,
      source_stats: sourceStats,
      source_names: [...new Set(sources.map(s => s.source_name))],
      prompt_types: Object.keys(systemPrompts),
      endpoints: {
        search: 'GET/POST with ?query=your+question',
        health: 'GET?action=health',
        all: 'GET?action=all',
        stats: 'GET?action=stats'
      },
      last_updated: lastUpdated
    });

  } catch (error) {
    console.error('API Error:', error.message);
    return res.status(500).json({
      error: 'Internal server error',
      message: error.message || 'Unknown error',
      timestamp: new Date().toISOString()
    });
  }
}
